------ROLES
grant create role to gol_pdb_A;

SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = gol_pdb_A;

CREATE ROLE SYSADMIN_ROLE;

CREATE ROLE CLIENT_ROLE;


GRANT CREATE SESSION TO SYSADMIN_ROLE;
GRANT EXECUTE ANY PROCEDURE TO SYSADMIN_ROLE;
GRANT CREATE SEQUENCE TO SYSADMIN_ROLE;
grant dba to SYSADMIN_role;


GRANT CREATE SESSION TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.AddReview TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.DeleteReview TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.AddRegistration TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.DeleteRegistration TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.GetClientRegistrations TO CLIENT_ROLE;
GRANT EXECUTE ON GetServiceList TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.GETEMPLOYEEList TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.GetServiceInfoByName TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.GetAverageRatingForEmployee TO CLIENT_ROLE;
GRANT EXECUTE ON GOL_PDB_A.GetReviewsForEmployee TO CLIENT_ROLE;
grant execute on GOL_PDB_A.RegisterClient to CLIENT_ROLE;
grant execute on GOL_PDB_A.UpdateClient to CLIENT_ROLE;
grant execute on GOL_PDB_A.DeleteClient to CLIENT_ROLE;
grant execute on GOL_PDB_A.ClientLogin to CLIENT_ROLE;
grant execute on GOL_PDB_A.GetClientInfoByID to CLIENT_ROLE;
grant execute on GOL_PDB_A.IsEmailValid to CLIENT_SALON;
grant execute on GOL_PDB_A.IsEmployeeExists to CLIENT_SALON;
grant execute on GOL_PDB_A.IsReviewExists to CLIENT_SALON;
grant execute on GOL_PDB_A.IsServiceExists to CLIENT_SALON;
grant execute on GOL_PDB_A.EnableDbmsOutput to CLIENT_SALON;
grant create session, connect to CLIENT_ROLE;




grant grant to GOL_PDB_A;
commit;

select * from dba_SYS_PRIVS where GRANTEE = 'SYSADMIN_ROLE';
select * from dba_SYS_PRIVS where GRANTEE = 'CLIENT_ROLE';

SELECT * FROM USER_ROLE_PRIVS;



CREATE PROFILE ANYPERSON_BASE_PROFILE LIMIT
  PASSWORD_LIFE_TIME 180
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME DEFAULT
  CONNECT_TIME 180
  IDLE_TIME 30;

COMMIT; 


-------------------------------
CREATE USER SYSADMIN IDENTIFIED BY SYSADMINPASS
  PROFILE ANYPERSON_BASE_PROFILE
  account unlock;
GRANT SYSADMIN_ROLE TO SYSADMIN;


CREATE USER CLIENT_SALON IDENTIFIED BY CLIENTPASS
  PROFILE ANYPERSON_BASE_PROFILE
  account unlock;
GRANT CLIENT_ROLE TO CLIENT_SALON;


--------------------------
drop user SYSADMIN;
drop profile ANYPERSON_BASE_PROFILE;
drop role SYSADMIN_ROLE;
drop user CLIENT_SALON;
drop user SYSADMIN;


